; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
build_unflags = -std=gnu++11 -std=c++11 -std=c++14
build_flags = -std=gnu++17

[env:tdm240x_dev_wifi]
platform = espressif32
board = esp32dev
framework = arduino
lib_ignore = 
	mockPubSubClient
	mockLoraWan
	mockWiFi
lib_deps = 
	knolleary/PubSubClient@^2.8
	vshymanskyy/TinyGSM@^0.12.0
	vshymanskyy/StreamDebugger@^1.0.1
check_src_filters = 
	+<**/*.cpp> +<**/*.h>
	-<src/hardware/Lora_handler.cpp>
	-<src/hardware/Sim_handler.cpp>
	-<include/hardware/Lora_handler.h>
	-<include/hardware/Sim_handler.h>
build_src_filter = 
	+<*>
	-<hardware/Lora_handler.cpp>
	-<hardware/Sim_handler.cpp>
monitor_speed = 115200
build_flags = -std=gnu++17 -DCONNECT_USING_WIFI=1 -DCONNECT_USING_4G=0 
	-DBOARD_TDM_240X -DRTCM_COMMUNICATION_PROTOCOL=0

[env:tdm240x_dev_wifi_test]
platform = espressif32
board = esp32dev
framework = arduino
lib_ignore = 
	mockPubSubClient
	mockLoraWan
	mockWiFi
lib_deps = 
	knolleary/PubSubClient@^2.8
	vshymanskyy/TinyGSM@^0.12.0
	vshymanskyy/StreamDebugger@^1.0.1
	levkovigor/PPPOSClient@^1.0
check_src_filters = 
	+<**/*.cpp> +<**/*.h>
	-<src/hardware/Lora_handler.cpp>
	-<src/hardware/Sim_handler.cpp>
	-<include/hardware/Lora_handler.h>
	-<include/hardware/Sim_handler.h>
build_src_filter = 
	+<*>
	-<hardware/Lora_handler.cpp>
	-<hardware/Sim_handler.cpp>
monitor_speed = 115200
build_flags = -std=gnu++17 -DCONNECT_USING_WIFI=1 -DCONNECT_USING_4G=0 -DPROGRAM_TEST
	-DBOARD_TDM_240X -DRTCM_COMMUNICATION_PROTOCOL=0 -DPROGRAM_DEBUG -DDUMP_AT_COMMANDS

[env:tdm240x_dev_4g]
platform = espressif32
board = esp32dev
framework = arduino
lib_ignore = 
	mockPubSubClient
	mockLoraWan
	mockWiFi
lib_deps = 
	knolleary/PubSubClient@^2.8
	vshymanskyy/TinyGSM@^0.12.0
	vshymanskyy/StreamDebugger@^1.0.1
check_src_filters = 
	+<**/*.cpp> +<**/*.h>
	-<src/hardware/Lora_handler.cpp>
	-<src/hardware/Wifi_handler.cpp>
	-<include/hardware/Lora_handler.h>
	-<include/hardware/Wifi_handler.h>
build_src_filter = 
	+<*>
	-<hardware/Lora_handler.cpp>
	-<hardware/Wifi_handler.cpp>
monitor_speed = 115200
build_flags = -std=gnu++17 -DCONNECT_USING_WIFI=0 -DCONNECT_USING_4G=1 
		-DBOARD_TDM_240X -DRTCM_COMMUNICATION_PROTOCOL=0

[env:tdm240x_dev_4g_debug]
platform = espressif32
board = esp32dev
framework = arduino
lib_ignore = 
	mockPubSubClient
	mockLoraWan
	mockWiFi
lib_deps = 
	knolleary/PubSubClient@^2.8
	vshymanskyy/TinyGSM@^0.12.0
	vshymanskyy/StreamDebugger@^1.0.1
check_src_filters = 
	+<**/*.cpp> +<**/*.h>
	-<src/hardware/Lora_handler.cpp>
	-<src/hardware/Wifi_handler.cpp>
	-<include/hardware/Lora_handler.h>
	-<include/hardware/Wifi_handler.h>
build_src_filter = 
	+<*>
	-<hardware/Lora_handler.cpp>
	-<hardware/Wifi_handler.cpp>
monitor_speed = 115200
build_flags = -std=gnu++17 -DCONNECT_USING_WIFI=0 -DCONNECT_USING_4G=1
		-DBOARD_TDM_240X -DRTCM_COMMUNICATION_PROTOCOL=0 -DPROGRAM_DEBUG -DDUMP_AT_COMMANDS

[env:tdm240x_dev_4g_test]
platform = espressif32
board = esp32dev
framework = arduino
lib_ignore = 
	mockPubSubClient
	mockLoraWan
	mockWiFi
lib_deps = 
	knolleary/PubSubClient@^2.8
	vshymanskyy/TinyGSM@^0.12.0
	vshymanskyy/StreamDebugger@^1.0.1
check_src_filters = 
	+<**/*.cpp> +<**/*.h>
	-<src/hardware/Lora_handler.cpp>
	-<src/hardware/Wifi_handler.cpp>
	-<include/hardware/Lora_handler.h>
	-<include/hardware/Wifi_handler.h>
build_src_filter = 
	+<*>
	-<hardware/Lora_handler.cpp>
	-<hardware/Wifi_handler.cpp>
monitor_speed = 115200
build_flags = -std=gnu++17 -DCONNECT_USING_WIFI=0 -DCONNECT_USING_4G=1 -DBOARD_TDM_240X
		-DRTCM_COMMUNICATION_PROTOCOL=0 -DPROGRAM_DEBUG -DPROGRAM_TEST -DDUMP_AT_COMMANDS

[env:tdm240x_dev_4g_unit_test]
platform = espressif32
board = esp32dev
framework = arduino
lib_ignore = 
	mockPubSubClient
	mockLoraWan
	mockWiFi
lib_deps = 
	knolleary/PubSubClient@^2.8
	vshymanskyy/TinyGSM@^0.12.0
	vshymanskyy/StreamDebugger@^1.0.1
check_src_filters = 
	+<**/*.cpp> +<**/*.h>
	-<src/hardware/Lora_handler.cpp>
	-<src/hardware/Wifi_handler.cpp>
	-<include/hardware/Lora_handler.h>
	-<include/hardware/Wifi_handler.h>
build_src_filter = 
	+<*>
	-<hardware/Lora_handler.cpp>
	-<hardware/Wifi_handler.cpp>
	-<main.cpp>
test_build_src = true
test_framework = unity
test_filter =
	test_sim
monitor_speed = 115200
build_flags = -std=gnu++17 -DCONNECT_USING_WIFI=0 -DCONNECT_USING_4G=1 -DBOARD_TDM_240X
		-DRTCM_COMMUNICATION_PROTOCOL=0 -DPROGRAM_DEBUG -DPROGRAM_TEST -DDUMP_AT_COMMANDS

[env:heltecv4_dev_wifi]
platform = espressif32
board = heltec_wifi_lora_32_V4
framework = arduino
lib_ignore = 
	mockPubSubClient
	mockLoraWan
	mockWiFi
lib_deps = 
	knolleary/PubSubClient@^2.8
	vshymanskyy/TinyGSM@^0.12.0
	vshymanskyy/StreamDebugger@^1.0.1
	heltecautomation/Heltec ESP32 Dev-Boards@^2.1.5
check_src_filters = 
	+<**/*.cpp> +<**/*.h>
	-<src/hardware/Sim_handler.cpp>
	-<src/hardware/Lora_handler.cpp>
	-<src/functions/Nmea_Receiver.cpp>
	-<include/hardware/Lora_handler.h>
	-<include/hardware/Sim_handler.h>
	-<include/functions/RTCM_Receiver.h>
build_src_filter = 
	+<*>
	-<hardware/Sim_handler.cpp>
	-<hardware/Lora_handler.cpp>
	-<functions/Nmea_Receiver.cpp>
board_build.variants_dir = variants
board_build.variant = heltec_V4
monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0
build_flags = -std=gnu++17 -DCONNECT_USING_WIFI=1 -DCONNECT_USING_4G=0 -DBOARD_HELTEC

[env:heltecv4_dev_lora]
platform = espressif32
board = heltec_wifi_lora_32_V4
framework = arduino
test_build_src = true
lib_ignore = 
	mockPubSubClient
	mockLoraWan
	mockWiFi
lib_deps = 
	knolleary/PubSubClient@^2.8
	vshymanskyy/TinyGSM@^0.12.0
	vshymanskyy/StreamDebugger@^1.0.1
	heltecautomation/Heltec ESP32 Dev-Boards@^2.1.5
check_src_filters = 
	+<**/*.cpp> +<**/*.h>
	-<src/hardware/Sim_handler.cpp>
	-<src/functions/NTRIP_Handler_IP.cpp>
	-<include/hardware/Sim_handler.h>
	-<include/functions/NTRIP_Handler_IP.h>
build_src_filter = 
	+<*>
	-<hardware/Sim_handler.cpp>
	-<functions/NTRIP_Handler_IP.cpp>
board_build.variants_dir = variants
board_build.variant = heltec_V4
monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0
build_flags = -std=gnu++17 -DCONNECT_USING_WIFI=1 -DCONNECT_USING_4G=0
	-DRTCM_COMMUNICATION_PROTOCOL=1 -DBOARD_HELTEC

[env:heltecv4_test_lora]
platform = espressif32
board = heltec_wifi_lora_32_V4
framework = arduino
test_build_src = true
test_framework = unity
lib_ignore = 
	mockPubSubClient
	mockLoraWan
	mockWiFi
lib_deps = 
	knolleary/PubSubClient@^2.8
	vshymanskyy/TinyGSM@^0.12.0
	vshymanskyy/StreamDebugger@^1.0.1
	heltecautomation/Heltec ESP32 Dev-Boards@^2.1.5
check_src_filters = 
	+<**/*.cpp> +<**/*.h>
	-<src/hardware/Sim_handler.cpp>
	-<src/functions/NTRIP_Handler_IP.cpp>
	-<include/hardware/Sim_handler.h>
	-<include/functions/NTRIP_Handler_IP.h>
	-<main.cpp>
build_src_filter = 
	+<*>
	-<hardware/Sim_handler.cpp>
	-<functions/NTRIP_Handler_IP.cpp>
	-<main.cpp>
test_filter =
	test_lora_long_term
board_build.variants_dir = variants
board_build.variant = heltec_V4
monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0
build_flags = -std=gnu++17 -DCONNECT_USING_WIFI=1 -DCONNECT_USING_4G=0
	-DRTCM_COMMUNICATION_PROTOCOL=1 -DBOARD_HELTEC -DUNIT_TEST -DUNITY_INCLUDE_DOUBLE
    -DUNITY_DOUBLE_PRECISION=1e-12